# Generated by Django 5.1.6 on 2025-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('Water', 'Water Department'), ('electricity', 'Electricity Department'), ('sanitation', 'Sanitation Department'), ('Road', 'Road Maintenance')], max_length=20),
        ),
    ]
