# Generated by Django 5.1.6 on 2025-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcsapp', '0003_admintoken_user_admin_user_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
